


import algoritmos.RC4;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.WritableRaster;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.nio.CharBuffer;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.io.IOUtils;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joseluisllinaresanton
 */
public final class PantallaCifrarFichero extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    private String rutica;
    private int pixeles;
    private BufferedReader in;
    private byte[] bytes;
    private String extension;
    private CharBuffer asciis;
    
    public PantallaCifrarFichero() {
        initComponents();
       
    }
    public PantallaCifrarFichero(String RutaImagen, String fichero) throws FileNotFoundException, IOException {
        initComponents();
        this.rutica = RutaImagen;
        VerImagen(RutaImagen);
        this.setTitle("Cifrando");
        extension = fichero.substring(fichero.indexOf(".")+1);
        InputStreamReader input = new InputStreamReader(new FileInputStream(fichero));
        in = new BufferedReader(input);
        bytes = IOUtils.toByteArray(in, "latin1");
        String s = new String(bytes);
        
        int valor = s.getBytes().length;
        this.jTextField1.setText(Integer.toString(valor));  
    }
    
    public void VerImagen(String ruta)
    {
        BufferedImage imagenEscalada = EscalarImagen(label_imagen.getWidth(), label_imagen.getHeight(), ruta);
        label_imagen.setIcon(new ImageIcon((Image)imagenEscalada));
    }
    
    public BufferedImage EscalarImagen(int WIDTH, int HEIGHT, String filename)
    {
        BufferedImage bi = null;
        try
        {
            ImageIcon icono = new ImageIcon(filename);
            bi = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = (Graphics2D) bi.createGraphics();
            g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING,RenderingHints.VALUE_RENDER_QUALITY));
            g2d.drawImage(icono.getImage(), 0, 0, WIDTH, HEIGHT, null);
        }
        catch (Exception e)
        {
            return null;
        }
        return bi;
    }
    

    public int valorDeClave(String clave)
    {
        int valor = 0;
        for(int i = 0; i<clave.length(); i++)
        {
            valor += clave.charAt(i);
        }
        return valor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        img_candado = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label_imagen = new javax.swing.JLabel();
        lbl_mensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1099, 575));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        img_candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lock77.png"))); // NOI18N

        jRadioButton1.setText("AES");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("RC4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(img_candado)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addGap(24, 24, 24)
                        .addComponent(jRadioButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(img_candado)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        label_imagen.setBackground(new java.awt.Color(204, 204, 204));

        lbl_mensaje.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lbl_mensaje.setForeground(new java.awt.Color(204, 204, 204));
        lbl_mensaje.setText("Tamaño en bytes del fichero a encriptar:");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tipo de cifrado");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Clave");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jButton1.setText("Ocultar Mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Imagen original");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Estadisticas");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Tiempo de cifrado:");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Tiempo de ocultacion:");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Pixeles modificados:");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel11)))))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(367, 367, 367))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_mensaje)
                                .addGap(307, 307, 307))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(352, 352, 352))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(label_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jPasswordField1.getText().length()>=5)
        {
            try {
                //pillamos la imagen que e muetra
                File imgPath = new File(rutica);
                    

                String clave = jPasswordField1.getText();
                //asignamos la clave
                int valorClave = valorDeClave(clave);
                long totalTime=0;
                long totalTimeOcultacion=0;
                String resultado="";
                int[] valores = new int[resultado.length()];
                
                if(jRadioButton1.isSelected()) //significa que se ha elegido AES
                {

                }
                else //significa que se ha elegido RC4. Aplica la encriptación al mensaje con la clave proporcionada.
                {
                    //Encriptamos
                    long startTime = System.currentTimeMillis();
                    RC4 rc4 = new RC4(clave);
                    
                    String mensaje = new String(bytes);
                    char[] result = rc4.encrypt(mensaje.toCharArray());
                    resultado = new String(result);   
                    System.out.println(resultado);
                    valores = new int[resultado.length()];
//                    System.out.println(asciis.get((byte)resultado.charAt(0) &0xFF)+"este es el 1");
                    for(int k = 0; k<resultado.length(); k++)
                    {
                        valores[k] = ((byte)resultado.charAt(k) & 0xFF);
                    }
                    long endTime   = System.currentTimeMillis();
                    totalTime = endTime - startTime;
                    
                }
                long startTime = System.currentTimeMillis();
                //Convertimos a binario cada uno de los bytes.
                int r =0;
                String[] almacen = new String[bytes.length];
                while(bytes.length>r)
                {
                    
                    String s1 = String.format("%8s", Integer.toBinaryString(valores[r])).replace(' ', '0');
                    almacen[r]= s1;
                    int charCode = Integer.parseInt(almacen[r], 2);
                    System.out.println(charCode);
                    r++;
                }
                System.out.println(almacen.length+"tamaño almacen");
                
                //abrimos la imagen.
                BufferedImage bufferedImage = null;
                try {
                    bufferedImage = ImageIO.read(imgPath);
                } catch (IOException ex) {
                    Logger.getLogger(PantallaCifrado.class.getName()).log(Level.SEVERE, null, ex);
                }
                int height = bufferedImage.getHeight();
                int width = bufferedImage.getWidth();

                WritableRaster raster = bufferedImage.getRaster();
                DataBufferByte data   = (DataBufferByte) raster.getDataBuffer();

                Random rnd = new Random();
                rnd.setSeed(data.getData().length+valorClave);  //la semilla será el valor de la clave + los datos.
                
                int i =0;
                while(i<almacen.length)
                {
                    for(int j = 0; j<8; j++)
                    {
                        int posicion = rnd.nextInt(((data.getData().length-1) - 1) + 1)+ 1;
                        data.getData()[posicion] = lsb(data.getData()[posicion], almacen[i].charAt(j));
                    }
                    i++;
                }
                //TODO que pille extension mas larga
                byte[] b = extension.getBytes();
                int k =0;
                String[] exten = new String[3];
                while(b.length>k)
                {
                    String s3 = String.format("%8s", Integer.toBinaryString(b[k] & 0xFF)).replace(' ', '0');
                    exten[k] = s3; 
                    k++;
                }
                
                
                //coge los nuevos datos y genera la nueva imagen.
                //TYPE_3BYTE_BGR
                BufferedImage newImage = new BufferedImage(width, height, bufferedImage.getType());
                WritableRaster rasterFinal = newImage.getRaster();
                rasterFinal.setDataElements(0, 0, width, height, data.getData());
                newImage.setData(raster);
                
                Color mycolor = new Color(Integer.parseInt(exten[0], 2),Integer.parseInt(exten[1], 2), Integer.parseInt(exten[2], 2));
                String bin = Integer.toBinaryString(almacen.length);
                String cadenaRojo ="";
                String cadenaVerde ="";
                String cadenaAzul ="";
                int contador=0;
                
                
                ArrayList<Color> tamColores = new ArrayList<Color>();
                
                for(int tamCadenaAlmacen=0; tamCadenaAlmacen<=bin.length();tamCadenaAlmacen++)
                {
                    int num = tamCadenaAlmacen%24;
                    if(tamCadenaAlmacen%24 == 0 && tamCadenaAlmacen != 0 || tamCadenaAlmacen==bin.length())
                    {
                        if(cadenaVerde.length()!=8)
                        {
                            int faltan = 8-cadenaVerde.length();
                            String auxiliar="";
                            if(faltan!=8)
                            {
                                for(int numerito = 0; numerito<faltan; numerito++)
                                {
                                    auxiliar+="0";
                                }
                                cadenaVerde = auxiliar.concat(cadenaVerde);
                            }
                            else
                            {
                                cadenaVerde = "0";
                            }
                        }
                        if(cadenaAzul.length()!=8)
                        {
                            int faltan = 8-cadenaAzul.length();
                            String auxiliar="";
                            if(faltan!=8)
                            {
                                for(int numerito = 0; numerito<faltan; numerito++)
                                {
                                    auxiliar+="0";   
                                }
                                cadenaAzul = auxiliar.concat(cadenaAzul);  
                            }
                            else
                            {
                                cadenaAzul="0";
                            }
                        }
                        Color myColorTam= new Color(Integer.parseInt(cadenaRojo, 2),Integer.parseInt(cadenaVerde, 2), Integer.parseInt(cadenaAzul, 2));
                        tamColores.add(myColorTam);
                        contador++;
                        cadenaRojo ="";
                        cadenaVerde ="";
                        cadenaAzul ="";
                        if(tamCadenaAlmacen==bin.length())
                        {
                            break;
                        }
                    }
                    if(num<8)
                    {
                        cadenaRojo += bin.charAt(tamCadenaAlmacen);
                    }
                    if(num>=8 && num<16)
                    {
                        cadenaVerde += bin.charAt(tamCadenaAlmacen);
                    }
                    if(num>=16 && num<24)
                    {
                        cadenaAzul += bin.charAt(tamCadenaAlmacen);
                    }
                }
                try {
                    //la posicion donde esta el tamaño tambien va escondida
                    //segun la clave y el tamaño de la imagen.
                    Random posiH = new Random();
                    posiH.setSeed(valorClave);
                    int posicionTamTextH = posiH.nextInt((newImage.getHeight() - 1) + 1)+ 1;
                    posicionTamTextH = posicionTamTextH/2;
                    System.out.println(posicionTamTextH);
                    Random posiW = new Random();
                    posiW.setSeed(valorClave);
                    int posicionTamTextW = posiW.nextInt((newImage.getWidth() - 1) + 1)+ 1;
                    posicionTamTextW = posicionTamTextW/2;
                    System.out.println(posicionTamTextW);
                    newImage.setRGB(posicionTamTextH, posicionTamTextW, mycolor.getRGB()); //asignamos la extension
                    Color total = new Color(tamColores.size(), 0,0);
                    newImage.setRGB(posicionTamTextH+1, posicionTamTextW+1, total.getRGB()); //aisgnamos el tamaño del archivo
                    for(int totalPixeles = 0; totalPixeles<tamColores.size(); totalPixeles++)
                    {
                        newImage.setRGB(posicionTamTextH+2+totalPixeles, posicionTamTextW+2+totalPixeles, tamColores.get(totalPixeles).getRGB()); //guardamos los pixeles donde estara escondido el tamaño del fichero.
                    }
                    ImageIO.write(newImage, "png", new File("/Users/joseluisllinaresanton/Desktop/fichero.png"));

                    BufferedImage imagenEscalada = EscalarImagen(label_imagen.getWidth(), label_imagen.getHeight(), "/Users/joseluisllinaresanton/Desktop/fichero.png");
                    label_imagen.setIcon(new ImageIcon((Image)imagenEscalada));
                    long EndTime = System.currentTimeMillis();
                    totalTimeOcultacion = EndTime - startTime;

                    jLabel4.setText(totalTime+ " milisegundos para cifrar el mensaje.");
                    jLabel10.setText(totalTimeOcultacion +" milisegundos para ocultar el mensaje.");
                    jLabel11.setText(pixeles + " modificados en total.");
                } catch (IOException ex)
                {
                    Logger.getLogger(PantallaCifrado.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (RC4.InvalidKeyException ex) {
                Logger.getLogger(PantallaCifrarFichero.class.getName()).log(Level.SEVERE, null, ex);
            } /*catch (UnsupportedEncodingException ex) {
                Logger.getLogger(PantallaCifrarFichero.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Tamaño de clave demasiado pequeña. Pruebe con otra.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected())
        {
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    public String convertirABinario(String message)
    {
        String bin = "";
        for (int i = 0; i < message.length(); i++)
        {
            bin += convertirLetraABinario(message.charAt(i));
        }
        return bin;
    }
    public String convertirLetraABinario(char caracter)
    {
        int x = (int)caracter;
        String binario = "";
        for (int i = 0; i < 8; i++)
        {
            binario = "" + (x % 2) + binario;
            x = x/ 2;
        }
        return binario;
    }
    
    public byte lsb(byte s, char seCambia)
    {
        String binario = byteABinario(s);
        
        if(binario.charAt(binario.length()-1)=='0' && seCambia=='1')
        {
            binario = binario.substring(0, binario.length()-1);
            binario += "1";
            pixeles += 1;
        }
        else if(binario.charAt(binario.length()-1)=='1' && seCambia=='0')
        {
            binario = binario.substring(0, binario.length()-1);
            binario += "0";
            pixeles += 1;
        }
        int decimalValue = Integer.parseInt(binario, 2);
        
        byte b  = (byte)decimalValue;       
        return b;
    }
    public String byteABinario(byte s)
    {
            int i2 = s & 0xFF;
            String binario = "";
            for (int i = 0; i < 8; i++)
            {
                binario = "" + (i2 % 2) + binario;
                i2 = i2/ 2;
            }
            return binario;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
               
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_candado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel lbl_mensaje;
    // End of variables declaration//GEN-END:variables
}
